"""new fields in user model

Revision ID: 66314bdd3f59
Revises: 294ffa052d0a
Create Date: 2018-06-17 13:41:24.435991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66314bdd3f59'
down_revision = '294ffa052d0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
