"""followers

Revision ID: 959b52fd611f
Revises: 66314bdd3f59
Create Date: 2018-06-17 15:39:56.148945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '959b52fd611f'
down_revision = '66314bdd3f59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follower',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follower')
    # ### end Alembic commands ###
